### libraries

In [1]:
import sklearn
import numpy as np
import pandas as pd
from numpy import asarray
import matplotlib.pyplot as plt
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures

## dataset 

In [2]:
dataset=pd.read_csv('dataset_q2_q4.csv')
dataset

x1          x2          x3       y_label
0   -100.838182  100.000000    0.000000 -6.908485e+06
1    -98.826004  101.202405    0.901804 -7.167624e+06
2    -98.627987  102.404810    1.803607 -7.429470e+06
3    -96.960173  103.607214    2.705411 -7.699765e+06
4    -97.190325  104.809619    3.607214 -7.972486e+06
..          ...         ...         ...           ...
495  294.786321  695.190381  446.392786  1.206979e+09
496  296.056099  696.392786  447.294589  1.216369e+09
497  297.526847  697.595190  448.196393  1.225805e+09
498  300.037521  698.797595  449.098196  1.235292e+09
499  299.092965  700.000000  450.000000  1.244805e+09

[500 rows x 4 columns]

In [3]:
X=dataset.drop('y_label', axis=1)
Y=dataset['y_label']

In [4]:
X=np.array(X)
Y=np.array(Y)


In [5]:
X1=X[:,0]
X2=X[:,1]
X3=X[:,2]
n=len(X1)
X_bais=np.ones((n,1))

In [6]:
X_new=np.append(X_bais,X,axis=1) #X
X_new

array([[   1.        , -100.83818183,  100.        ,    0.        ],
       [   1.        ,  -98.82600411,  101.20240481,    0.90180361],
       [   1.        ,  -98.62798713,  102.40480962,    1.80360721],
       ...,
       [   1.        ,  297.52684714,  697.59519038,  448.19639279],
       [   1.        ,  300.03752102,  698.79759519,  449.09819639],
       [   1.        ,  299.09296483,  700.        ,  450.        ]])

In [7]:
X_new_Transpose=np.transpose(X_new) #X.T
X_new_Transpose

array([[   1.        ,    1.        ,    1.        , ...,    1.        ,
           1.        ,    1.        ],
       [-100.83818183,  -98.82600411,  -98.62798713, ...,  297.52684714,
         300.03752102,  299.09296483],
       [ 100.        ,  101.20240481,  102.40480962, ...,  697.59519038,
         698.79759519,  700.        ],
       [   0.        ,    0.90180361,    1.80360721, ...,  448.19639279,
         449.09819639,  450.        ]])

In [8]:
X_new_Transpose_dot_X_new=X_new_Transpose.dot(X_new) #X X.T
X_new_Transpose_dot_X_new

array([[5.00000000e+02, 4.99774068e+04, 2.00000000e+05, 1.12500000e+05],
       [4.99774068e+04, 1.16915049e+07, 3.00326271e+07, 1.87761648e+07],
       [2.00000000e+05, 3.00326271e+07, 9.50601202e+07, 5.62950902e+07],
       [1.12500000e+05, 1.87761648e+07, 5.62950902e+07, 3.37838176e+07]])

In [9]:
temp1=np.linalg.inv(X_new_Transpose_dot_X_new) #(X X.T) inverse
temp2=X_new_Transpose.dot(Y) # X.T * Y

In [10]:
theta=temp1.dot(temp2) #(X X.T)invers * X.T * Y
theta

array([-1.87904819e+09, -1.31837709e+07,  2.35929600e+06,  1.15343360e+07])

In [11]:
theta_0=theta[0]
theta_1=theta[1]
theta_2=theta[2]
theta_3=theta[3]
print(theta_0,'\n',theta_1,'\n',theta_2,'\n',theta_3)

-1879048192.0 
 -13183770.853199005 
 2359296.0 
 11534336.0


## To check from Model

In [12]:
def pred_value(theta_0,theta_1,theta_2,theta_3,X1,X2,X3):
    # preparing each term of hypothises
    term1=3*theta_1*X1**2
    term2=theta_2*X2**3
    term3=-theta_3*X2**3
    term4=theta_2*theta_3*X3**3
    
    predict_value=term1+term2+term3+term4+theta_0              
    #hypothises of linear regression(theta_0+theta_1*X1+theta_2*X2+theta_3*X3)
    return predict_value

In [13]:
X1=-100.838182
X2=100.000000
X3=0.000000
lable=pred_value(theta_0,theta_1,theta_2,theta_3,X1,X2,X3)
lable

-9579090200178.398